name: Generate and Upload MMA Activity

on:
  workflow_dispatch:

jobs:
  mma-activity:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install garminconnect

      - name: Set Garmin credentials
        env:
          GARMIN_USER: ${{ secrets.GARMIN_USER }}
          GARMIN_PASS: ${{ secrets.GARMIN_PASS }}
        run: |
          echo "Garmin credentials set as environment variables"

      - name: Build and run C# console app
        run: dotnet run --project FitChamp/FitChamp.csproj

      - name: Upload FIT file with Python
        run: python upload_to_garmin.py
        env:
          GARMIN_USER: ${{ secrets.GARMIN_USER }}
          GARMIN_PASS: ${{ secrets.GARMIN_PASS }}
