name: Garmin Ringen Upload

on:
  workflow_dispatch:  # manuelles Auslösen

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Repo auschecken
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Abhängigkeiten installieren
        run: |
          pip install -r requirements.txt

      - name: FIT-Datei erzeugen & hochladen
        env:
          GARMIN_USER: ${{ secrets.GARMIN_USER }}
          GARMIN_PASS: ${{ secrets.GARMIN_PASS }}
        run: |
          python fitgen.py
